os: osx
language: node_js
node_js: '10'

before_cache:
  - brew cleanup

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
    - "$HOME/Library/Caches/Homebrew"

jobs:
  include:
#    - stage: build
#      name: "Build Angular App"
#      script: './scripts/ci/build-ng.sh'
#    - # parallel run
#      name: "Build Electron App"
#      script: './scripts/ci/build-electron.sh'
#    - stage: test
#      name: "Run BurstJS Tests"
#      script: './scripts/ci/test-burstjs.sh'
#    - # parallel run
#      name: "Run Angular Tests"
#      script: './scripts/ci/test-ng.sh'
#    - stage: deploy
#      name: "Build and Deploy Desktop App"
#      script: './scripts/ci/release-desktop.sh'
#    - stage: deploy-force
#      name: "Forced Build and Deploy Desktop App"
#      script: './scripts/ci/release-desktop.sh --force'
    - stage: nightly-release
      name: "Nightly Release of Desktop App"
      script: './scripts/ci/nightly-desktop.sh'

stages:
  - build
  - test
#  - name: deploy
#    if: branch=~/^v\d+\.\d+\.\d+/
#  - name: deploy-force
#    if: branch=~/^force-deploy/
  - name: nightly-release
    if: (branch=nightly) AND (tag IS blank)
