language: node_js
matrix:
  fast_finish: true
  include:
  - name: Build BurstJS
    os: linux
    node_js: '10'
    env: JOB=burstjs
  - name: Build Web Wallet
    os: linux
    node_js: '10'
    env: JOB=web
  - name: Build Desktop Wallet
    if: branch=~ /^force-deploy-/
    os: osx
    node_js: '10'
    env: JOB=desktop-osx

before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- "./scripts/ci/$JOB.sh"
