language: node_js
node_js: '10'

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

jobs:
  include:
#    - stage: build
#      os: linux
#      name: "Build Angular App"
#      script: './scripts/ci/build-ng.sh'
##    - # parallel run
##      name: "Build Electron App"
##      script: './scripts/ci/build-electron.sh'
#    - stage: test
#      os: linux
#      name: "Run BurstJS Tests"
#      script: './scripts/ci/test-burstjs.sh'
#    - # parallel run
#      name: "Run Angular Tests"
#      script: './scripts/ci/test-ng.sh'
    - stage: deploy
      os: osx
      name: "Build and Deploy Desktop App"
      script: './scripts/ci/release-desktop.sh'

stages:
  - build
  - test
  - name: deploy
    if: branch=~/^v\d+\.\d+\.\d+|force-deploy/
