language: node_js
node_js: '10'

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

jobs:
  include:
    - stage: test
      os: linux
      script: './scripts/ci/test-burstjs.sh'
    - # parallel run
      script: './scripts/ci/test-ng.sh'
    - # parallel run
      script: './scripts/ci/build-ng.sh'

