os: osx
language: node_js
node_js: '10'
addons:
  homebrew:
    packages:
      - rpm

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

jobs:
  include:
#    - stage: build
#      name: "Build Angular App"
#      script: './scripts/ci/build-ng.sh'
#    - # parallel run
#      name: "Build Electron App"
#      script: './scripts/ci/build-electron.sh'
#    - stage: test
#      name: "Run BurstJS Tests"
#      script: './scripts/ci/test-burstjs.sh'
#    - # parallel run
#      name: "Run Angular Tests"
#      script: './scripts/ci/test-ng.sh'
#    - stage: deploy
#      name: "Build and Deploy Desktop App"
#      script: './scripts/ci/release-desktop.sh'
#    - stage: deploy-force
#      name: "Forced Build and Deploy Desktop App"
#      script: './scripts/ci/release-desktop.sh --publish'
    - stage: nightly-release
      name: "Nightly Release of Desktop App"
      script: './scripts/ci/nightly-desktop.sh'
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name $GIT_NAME
        - git config --local user.email $GIT_EMAIL
        - export TRAVIS_TAG=nightly
        - git tag $TRAVIS_TAG --force
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file:
          - ./README.md
#          - /desktop/wallet/release-builds/latest*
#          - /desktop/wallet/release-builds/Phoenix*
#          - /desktop/wallet/release-builds/phoenix*
        skip_cleanup: true
        overwrite: true
        on:
          branch: nightly
          condition: $TRAVIS_TAG=nightly

stages:
  - build
  - test
#  - name: deploy
#    if: branch=~/^v\d+\.\d+\.\d+/
#  - name: deploy-force
#    if: branch=~/^force-deploy/
  - name: nightly-release
    if: (branch=nightly) AND (tag IS blank)
