os: osx
language: node_js
node_js: '12'
addons:
  homebrew:
    packages:
      - rpm

cache:
  directories:
    # - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

before_script:
  - npm i @angular/cli -g

jobs:
  include:
    - stage: prepare
      name: "Run BurstJS Tests"
      script: './scripts/ci/test-burstjs.sh'
    - # parallel run
      name: "Bundle BurstJS"
      script: './scripts/ci/bundle-burstjs.sh'
    - # parallel run
      name: "Run Angular Tests"
      script: './scripts/ci/test-ng.sh'
    - stage: build
      name: "Build Desktop App"
      script: './scripts/ci/build-electron.sh'
    - stage: deploy
      name: "Build and Deploy Desktop App"
      script: './scripts/ci/release-desktop.sh --publish'
    - # parallel run
      name: "Build and Deploy Web App"
      script: './scripts/ci/build-web.sh'
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file: "./web/angular-wallet/web-phoenix-burst-wallet.tar.gz"
        skip_cleanup: true
#    - stage: nightly-release
#      name: "Nightly Release of Desktop App"
#      script: './scripts/ci/nightly-desktop.sh'

stages:
  - prepare
  - name: build
    if: type != cron AND tag !~ /^desktop-\d+\.\d+\.\d+/ AND branch !~ /^force-deploy/
  - name: deploy
    # TODO: rename tag - but would affect auto updater
    if: tag =~ /^desktop-\d+\.\d+\.\d+/- OR branch =~ /^force-deploy/
#  - name: nightly-release
#    if: branch=develop AND type=cron
